global:
  worker:
    registrationKeySecret:
      name:
      key:

# The ID of this cluster.
envoyClusterId: local-cluster-id

proxy:
  # Address of the proxy, in host:port format.
  address: session-manager-server-worker-service-http:8082
  http:
    # pool size of the HTTP tunnel
    poolSize: 3
  connect:
    # pool size of the HTTP upgrade tunnel
    poolSize: 10

httpPort: 8080

# Enable debug logging (true or false).
debugLogging: true

replicaCount: 1

serviceAccount:
  create: true

readinessProbe:
  successThreshold: 1
  failureThreshold: 3
  periodSeconds: 60
  timeoutSeconds: 5
  initialDelaySeconds: 5

image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/session-manager-agent
  pullPolicy: IfNotPresent

version:
