apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "session-manager-server.fullname" . }}
  labels:
    {{- include "session-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    admin:
      port: {{ .Values.adminPort }}
    server:
      port: {{ .Values.httpPort }}
      agentPort: {{ .Values.workerServiceHttpPort }}
      {{- if .Values.tls.enable }}
      tls:
        cert: /var/run/tls/tls.crt
        key: /var/run/tls/tls.key
      {{- end }}
      auth:
        {{- if .Values.global.auth.enable }}
        rbacServer:
          addr: {{ .Values.global.auth.rbacInternalServerAddr }}
        {{- end }}
      allowedOriginHosts:
      {{- toYaml .Values.allowedOriginHosts | nindent 6 }}
