apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "session-manager-server.fullname" . }}
  labels:
    {{- include "session-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    admin:
      port: {{ .Values.adminPort }}
    server:
      port: {{ .Values.httpPort }}
      agentPort: {{ .Values.agentHttpPort }}
      {{- if .Values.tls.enable }}
      tls:
        cert: /var/run/tls/tls.crt
        key: /var/run/tls/tls.key
      {{- end }}
      auth:
        {{- if .Values.auth.jwks.enable }}
        jwks:
          url: {{ .Values.auth.jwks.Url }}
          refreshInterval: {{ .Values.auth.jwks.certRefreshInterval }}
        {{- end }}
        {{- if .Values.global.auth.enable }}
        rbacServer:
          addr: {{ .Values.global.auth.rbacInternalServerAddr }}
        {{- end }}
      identifier:
        static:
          id: {{ .Values.identifier.static.id }}
      baseUrl: {{ .Values.baseUrl }}
      allowedOriginHosts:
      {{- toYaml .Values.allowedOriginHosts | nindent 6 }}
