apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "session-manager-server.fullname" . }}-http
  labels:
    {{- include "session-manager-server.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  rules:
  - http:
      paths:
      - path: /v1/sessions
        pathType: Prefix
        backend:
          service:
            name: {{ include "session-manager-server.fullname" . }}-http
            port:
              number: {{ .Values.httpPort }}
