apiVersion: v1
kind: Service
metadata:
  name: {{ include "session-manager-server.fullname" . }}-http
  labels:
    {{- include "session-manager-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.httpPort }}
    targetPort: http
  selector:
    {{- include "session-manager-server.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "session-manager-server.fullname" . }}-worker-service-http
  labels:
    {{- include "session-manager-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.workerServiceHttpPort }}
    targetPort: ws-http
  selector:
    {{- include "session-manager-server.selectorLabels" . | nindent 4 }}
