apiVersion: v1
kind: Service
metadata:
  name: {{ include "session-manager-server.fullname" . }}-http
  labels:
    {{- include "session-manager-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.httpPort }}
    targetPort: http
  selector:
    {{- include "session-manager-server.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "session-manager-server.fullname" . }}-worker-service-http
  labels:
    {{- include "session-manager-server.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.workerServiceHttpService.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.workerServiceHttpService.type }}
  {{- if .Values.workerServiceHttpService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.workerServiceHttpService.externalTrafficPolicy }}
  {{- end }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.workerServiceHttpService.port }}
    targetPort: ws-http
    {{- if .Values.workerServiceHttpService.nodePort }}
    nodePort: {{ .Values.workerServiceHttpService.nodePort }}
    {{- end }}
  selector:
    {{- include "session-manager-server.selectorLabels" . | nindent 4 }}
