global:
  llmOperatorBaseUrl:

  auth:
    enable: true
    oidcIssuerUrl:
    rbacInternalServerAddr:

  ingress:
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

  workerServiceIngress:
    create: false
    ingressClassName:
    tls:
      hosts:
      secretName:

httpPort: 8080
adminPort: 8081
workerServiceHttpPort: 8082

workerServiceHttpService:
  type: ClusterIP
  port: 8082
  nodePort:
  annotations:
  externalTrafficPolicy:
  loadBalancerSourceRanges:

tls:
  enable: false
  secretName:

allowedOriginHosts:
- localhost

auth:
  oidcClientId: session-manager
  oidcClientSecret: o15FQlUB8SeOOBiw3Pg5vD5p
  resolverAddr: localhost:8080
  cacheExpiration: 1m
  cacheCleanup: 15m

debugLog: false

image:
  repository: public.ecr.aws/cloudnatix/llm-operator/session-manager-server
  pullPolicy: IfNotPresent

replicaCount: 1

podAnnotations:
nodeSelector:
affinity:
tolerations:

version:
