global:
  auth:
    enable: true
    rbacInternalServerAddr:

auth:
  jwks:
    enable: false
    url:
    certRefreshInterval:

identifier:
  static:
    id: local-cluster

baseUrl: /v1/sessions

httpPort: 8080
adminPort: 8081
agentHttpPort: 8082

tls:
  enable: false
  secretName:

allowedOriginHosts:
- localhost

debugLog: false

image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/session-manager-server
  pullPolicy: IfNotPresent

replicaCount: 1