global:
  auth:
    enable: true
    rbacInternalServerAddr:

  ingress:
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

  workerServiceIngress:
    create: false
    ingressClassName:
    tls:
      hosts:
      secretName:

httpPort: 8080
adminPort: 8081
workerServiceHttpPort: 8082

tls:
  enable: false
  secretName:

allowedOriginHosts:
- localhost

debugLog: false

image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/session-manager-server
  pullPolicy: IfNotPresent

replicaCount: 1